// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iowpibyaavsbxqoahwwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvd3BpYnlhYXZzYnhxb2Fod3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MDg1NjIsImV4cCI6MjA1MzE4NDU2Mn0.JzSHjgceu-4FD1tbrpFN8jqhT6or6i6gqwHfzR6amjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);